version: '3.9'
services:
  # mongo:
  #     container_name: mongodb
  #     image: mongo
  #     restart: always
  #     volumes: 
  #       - db-volume:/data/db
  #     ports:
  #       - 27017:27017 
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - 3306:3306
  app:
    container_name: nodeapp
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
volumes:
  db-volume: