version: '3.9'
services:
  # mongo:
  #     container_name: mongodb
  #     image: mongo
  #     restart: always
  #     volumes: 
  #       - db-volume:/data/db
  #     ports:
  #       - 27017:27017 
  mysql:
    container_name: mysql
    image: mysql:5.7
    user: root
    networks:
      - backend
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=guiapress
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
      - ./data/:/var/lib/mysql
  app:
    container_name: app
    build: .
    volumes:
      - ./:/home/node/app
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql  
    networks:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./:/home/node/app
    
networks:
  backend: 
    driver: bridge